adding tag-cloud components
HunkevychPhilip/Oxford-Dictionaries-client pull request #5
Opened 2020-09-23 07:49 UTC by HunkevychPhilip

An initial set of tag-cloud component files

2020-09-23 12:08 UTC, yderevianko-cartera requested changes
Please fix merge conflicts

2020-09-23 12:08 UTC, yderevianko-cartera commented on src/Controller/TagCloudController.php
> +        return $this->render('tag_cloud/index.html.twig', [
missed empty line before return

2020-09-23 12:08 UTC, yderevianko-cartera commented on src/Controller/TagCloudController.php
> +    public function getData()
should be empty line before new function/method

2020-09-23 12:08 UTC, yderevianko-cartera commented on src/Controller/TagCloudController.php
> +            if ($counter > $maximum) $maximum = $counter;
always use { and } in if statements and remove not needed empty lines and comments

2020-09-23 12:08 UTC, yderevianko-cartera commented on src/Repository/SearchesRepository.php
> +
not needed empty lines

2020-09-24 10:33 UTC, CoremanY approved these changes

2020-09-24 10:40 UTC, merged